import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Noto_Sans_Thai } from 'next/font/google';
import './globals.css';

// โหลดฟอนต์ Noto Sans Thai
const notoSansThai = Noto_Sans_Thai({
  subsets: ['thai', 'latin'],
  weight: ['100', '300', '400', '500', '700'],
  variable: '--font-noto-sans-thai',
});

export const metadata: Metadata = {
  title: "WellWave",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSansThai.variable}>
      <body
        className={notoSansThai.variable}
      >        <Navbar />
        {children}
      </body>
    </html>
  );
}
