import type { Metadata } from "next";
import "./globals.css";
// import NavbarWrapper from "./components/NavbarWrapper"; // ใช้ NavbarWrapper แทน Navbar
import { Noto_Sans_Thai } from 'next/font/google';
// import { cookies } from "next/headers";
// import { redirect } from "next/navigation";
import NavbarWrapper from "./components/NavbarWrapper";
const notoSansThai = Noto_Sans_Thai({
  subsets: ['thai', 'latin'],
  weight: ['100', '300', '400', '500', '700'],
  variable: '--font-noto-sans-thai',
});

export const metadata: Metadata = {
  title: "WellWave",
  description: "Generated by create next app",
  icons: {
    icon: "/wellwave.svg",
    shortcut: "/welwave.svg"
  }
};

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en" className={notoSansThai.variable}>
//       <body className={notoSansThai.variable}>
//         {/* <NavbarWrapper /> ใช้ NavbarWrapper แทน Navbar */}
//         {children}
//       </body>
//     </html>
//   );
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // const token = cookies().get("auth_token"); // ดึง Token เพื่อตรวจสอบการล็อกอิน

  // if (!token) {
  //   redirect("/login"); // ถ้าไม่มี Token → ไป Login
  // }

  return (
    <html lang="en">
      <body className={notoSansThai.variable}>
        <NavbarWrapper />
        {children}
      </body>
    </html>
  );
}
// export default async function RootLayout({ children }: { children: React.ReactNode }) {
//   // ใช้ await กับ cookies() เพื่อให้ได้ค่าที่ไม่ใช่ Promise
//   const token = (await cookies()).get("accessToken"); // ดึง Token จาก cookies

//   // if (!token) {
//   //   redirect("/login"); // ถ้าไม่มี Token → ไป Login
//   // }

//   return (
//     <html lang="en">
//       <body className={notoSansThai.variable}>
//         <NavbarWrapper /> {/* แสดง Navbar ทุกหน้า */}
//         <main className="p-4">{children}</main> {/* แสดงเนื้อหาหน้าเว็บ */}
//       </body>
//     </html>
//   );
// }