import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Noto_Sans_Thai } from 'next/font/google';
import './globals.css';

const notoSansThai = Noto_Sans_Thai({
  subsets: ['thai', 'latin'],
  weight: ['100', '300', '400', '500', '700'],
  variable: '--font-noto-sans-thai',
});

export const metadata: Metadata = {
  title: "WellWave",
  description: "Generated by create next app",
  icons: {
    icon: "/wellwave.svg", // ไฟล์ favicon.ico ใน public folder
    shortcut: "/welwave.svg"}
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSansThai.variable}>
      <body
        className={notoSansThai.variable}
      >        <Navbar />
        {children}
      </body>
    </html>
  );
}
